STR = "TEXT"
INT = "BIGINT"
FLOAT = "FLOAT"



CREATE = " CREATE "
DROP = " DROP "
USE = " USE "
TABLE = " TABLE "
TABLES = " TABLES "
DATABASE = " DATABASE "
DATABASES = " DATABASES "
SHOW = " SHOW "
COLUMNS = " COLUMNS "
FROM = " FROM "
INSERT = " INSERT "
INTO = " INTO "
VALUES = " VALUES "
